### PR TITLE
Development

### PR DESCRIPTION
**Pull request by vieiramanda11**

### CODE REVIEW

**Comment by vieiramanda11** [comment]
Hey.
Thank you in advance for your code review.
Amanda

**Comment by AdnanAfsari** [comment]
### **ADNAN AFSARI WORKING ON IT**

**Review by AdnanAfsari — APPROVED** [review]
Hello @vieiramanda11 Congratulations 👍 

Looks good so you can merge the branch and move one 😄 

**Friendly reminder: You should use Github/Git Flow in this project. However, changing it now would take too much time.
Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.**

Happy Coding

**Comment by vieiramanda11** [comment]
> .

Thank you for your feedback, @AdnanAfsari. Can you please tell me what I did wrong about Github/Git flow? I created a branch called methods to write the code, when I finished I open a pull request to merge with the development branch and then I fixed the linters erros and for the final step I created another pull-request to merge with the master. I'm looking foward to your response! Cheers,
Amanda.

**Comment by vieiramanda11** [comment]
> Hello @vieiramanda11 Congratulations +1
> 
> Looks good so you can merge the branch and move one smile
> 
> **Friendly reminder: You should use Github/Git Flow in this project. However, changing it now would take too much time. Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.**
> 
> Happy Coding

Captura de tela de 2019-08-08 23-09-22
Captura de tela de 2019-08-08 23-09-50
Captura de tela de 2019-08-08 23-10-03

**Comment by AdnanAfsari** [comment]
Hi @vieiramanda11 

Thanks for asking.
You should create pull request from "Feature-branch to development" not "development to master".
When you get 👍 , you merge your pull request and after that you merge your fresh development to master.
Screenshot 2019-08-09 at 8 51 53 AM

I hope you understand now , if you still have some confusions.please reach out to me in slack 😄 

Thanks

**Pull request merged**
